// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: inventory-service.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для запроса резервирования товара
type ReserveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductRequest) Reset() {
	*x = ReserveProductRequest{}
	mi := &file_inventory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductRequest) ProtoMessage() {}

func (x *ReserveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Сообщение для ответа на резервирование товара
type ReserveProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductResponse) Reset() {
	*x = ReserveProductResponse{}
	mi := &file_inventory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductResponse) ProtoMessage() {}

func (x *ReserveProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Сообщение для запроса компенсации товара
type CompensateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensateProductRequest) Reset() {
	*x = CompensateProductRequest{}
	mi := &file_inventory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensateProductRequest) ProtoMessage() {}

func (x *CompensateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensateProductRequest.ProtoReflect.Descriptor instead.
func (*CompensateProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{2}
}

func (x *CompensateProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CompensateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Сообщение для ответа на компенсацию товара
type CompensateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensateProductResponse) Reset() {
	*x = CompensateProductResponse{}
	mi := &file_inventory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensateProductResponse) ProtoMessage() {}

func (x *CompensateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensateProductResponse.ProtoReflect.Descriptor instead.
func (*CompensateProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{3}
}

func (x *CompensateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompensateProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inventory_service_proto protoreflect.FileDescriptor

const file_inventory_service_proto_rawDesc = "" +
	"\n" +
	"\x17inventory-service.proto\x12\x17api.v1.inventoryservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x15ReserveProductRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\"L\n" +
	"\x16ReserveProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x18CompensateProductRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\"O\n" +
	"\x19CompensateProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc4\x02\n" +
	"\x10InventoryService\x12\x90\x01\n" +
	"\x0eReserveProduct\x12..api.v1.inventoryservice.ReserveProductRequest\x1a/.api.v1.inventoryservice.ReserveProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/inventory/reserve\x12\x9c\x01\n" +
	"\x11CompensateProduct\x121.api.v1.inventoryservice.CompensateProductRequest\x1a2.api.v1.inventoryservice.CompensateProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/inventory/compensateBs\x92A`\x12:\n" +
	"\x11Inventory service\x12\x1eService for managing inventory2\x051.0.02\x10application/json:\x10application/jsonZ\x0epkg/api/v1;apib\x06proto3"

var (
	file_inventory_service_proto_rawDescOnce sync.Once
	file_inventory_service_proto_rawDescData []byte
)

func file_inventory_service_proto_rawDescGZIP() []byte {
	file_inventory_service_proto_rawDescOnce.Do(func() {
		file_inventory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)))
	})
	return file_inventory_service_proto_rawDescData
}

var file_inventory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inventory_service_proto_goTypes = []any{
	(*ReserveProductRequest)(nil),     // 0: api.v1.inventoryservice.ReserveProductRequest
	(*ReserveProductResponse)(nil),    // 1: api.v1.inventoryservice.ReserveProductResponse
	(*CompensateProductRequest)(nil),  // 2: api.v1.inventoryservice.CompensateProductRequest
	(*CompensateProductResponse)(nil), // 3: api.v1.inventoryservice.CompensateProductResponse
}
var file_inventory_service_proto_depIdxs = []int32{
	0, // 0: api.v1.inventoryservice.InventoryService.ReserveProduct:input_type -> api.v1.inventoryservice.ReserveProductRequest
	2, // 1: api.v1.inventoryservice.InventoryService.CompensateProduct:input_type -> api.v1.inventoryservice.CompensateProductRequest
	1, // 2: api.v1.inventoryservice.InventoryService.ReserveProduct:output_type -> api.v1.inventoryservice.ReserveProductResponse
	3, // 3: api.v1.inventoryservice.InventoryService.CompensateProduct:output_type -> api.v1.inventoryservice.CompensateProductResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_service_proto_init() }
func file_inventory_service_proto_init() {
	if File_inventory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_proto_goTypes,
		DependencyIndexes: file_inventory_service_proto_depIdxs,
		MessageInfos:      file_inventory_service_proto_msgTypes,
	}.Build()
	File_inventory_service_proto = out.File
	file_inventory_service_proto_goTypes = nil
	file_inventory_service_proto_depIdxs = nil
}
